version: "3.8"

services:
  hemort:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./static:/app/static:ro
    environment:
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
    restart: unless-stopped
